version: "3.5"
services:

  calendario_pg_db:
    container_name: calendario_pg_db
    image: postgres
    environment:
      POSTGRES_DB: "calendario_db"
      POSTGRES_USER: "calendario_db_user"
      POSTGRES_PASSWORD: "calendario_db_password"
    ports:
    - "5432:5432"

  calendario:
    container_name: calendario
    build:
      context: .
      dockerfile: calendario.dockerfile
    volumes:
      - $PWD:/app
#    env_file:
#      - .env
    ports:
      - "8080:8080"
    depends_on:
      - calendario_pg_db
    stop_signal: SIGINT
    environment:
      DEBUG: "1"
    command: ["./wait-for-postgres.sh", "db", "python", "run.py"]