version: "3.5"
services:

  calendario_pg_db:
    container_name: calendario_pg_db
    image: postgres
    environment:
      POSTGRES_DB: "calendario_db"
      POSTGRES_USER: "calendario_db_user"
      POSTGRES_PASSWORD: "calendario_db_password"
    ports:
    - "5432:5432"

  calendario_be:
    container_name: calendario_be
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    volumes:
      - $PWD/backend/app:/app
#    env_file:
#      - .env
    ports:
      - "8080:8080"
    depends_on:
      - calendario_pg_db
    stop_signal: SIGINT
    environment:
      DEBUG: "1"
      POSTGRES_SERVER: "calendario_pg_db"
    command: ["python", "run.py"]

  calendario_fe:
    container_name: calendario_fe
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - calendario_be
